#!/bin/sh
set -ex

# Check to make sure that module loads haven't been duplicated.
# Since this is potential minefield that could cause chaos, and a fix is
# currently in the Ubuntu delta, check specifically for it.

# Why is this so bad? See:
#   https://bugs.launchpad.net/ubuntu/+source/apache2/+bug/1251939
#   https://issues.apache.org/bugzilla/show_bug.cgi?id=55787

TEMPFILE0=$(mktemp)
TEMPFILE1=$(mktemp)
TEMPFILE2=$(mktemp)

apache2ctl -l -M > $TEMPFILE0
sort $TEMPFILE0 > $TEMPFILE1
if ! grep core.c $TEMPFILE1 ; then
	echo "core.c not found in apach2ctl output. apache2ctl broken?"
	exit 1
fi

uniq < $TEMPFILE1 > $TEMPFILE2

if ! diff -u $TEMPFILE1 $TEMPFILE2 ; then
	echo Duplicate module loads found
	exit 1
fi
